{% set versions = {
    "HEAD": "49e578d286cc0abdfbe92cdd5a643ad893b7a619",
    "0.3.0": "9d723bd21ccabb8cb5b0025edfd28305a037f8a5"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', 'minio-cpp')|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://github.com/minio/minio-cpp"
  git_rev: {{ versions.get(version, "HEAD") }}
  patches:
    - patches/0001-update-cmake.patch

requirements:
  build:
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('c') }}   # [linux]
    - {{ stdlib('c') }}

    - cmake
    - vcpkg
    - make

  host:
    - inih
    - curlpp
    - nlohmann_json
    - pugixml
    - zlib

  run:
    - inih
    - curlpp
    - nlohmann_json
    - pugixml
    - zlib

about:
  home: "https://github.com/minio/minio-cpp"
  license: "GPL-3.0"
  summary: "MinIO C++ Client SDK for Amazon S3 Compatible Cloud Storage"
  description: |
    MinIO C++ SDK is Simple Storage Service (aka S3) client to perform bucket and object operations to any Amazon S3 compatible object storage service.

extra:
  recipe-maintainers:
    - meiyasan
